### ISSUE TITLE
Null deref

### ISSUE THREAD

**Issue by cybercamphackathon** [MontseHack/CryptoClima#5]
https://github.com/MontseHack/CryptoClima/blob/master/Arduino/main.ino#L56

**Comment by cybercamphackathon** [comment]
Do not define variables in the same line after an assignment. it makes the code confusing to follow.

Check the values after strchr/... it may be null

**Comment by MontseHack** [comment]
Ok, we will care about the legibility.
On the other hand, that string comes from the ESP8266, which always separate the content of the message and its header with a ':'.
